BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 20
  LR: 9e-3
  LOSS: MSE
  MODEL_FILE_NAME: UBFC_Deepphys
  DATA:
    FS: 30
    DATASET: UBFC
    SPECIFIC: default
    DO_PREPROCESS: false
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/chainshoetall/My Passport/rPPG-dataset/UBFC_RPPG/raw_data/DATASET_2" 
    CACHED_PATH: "/media/chainshoetall/My Passport/rPPG-dataset/UBFC_RPPG/Preprocessed" 
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: true
      CHUNK_LENGTH: 128
      DYNAMIC_DETECTION: false
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: true
      LARGE_FACE_BOX: true
      LARGE_BOX_COEF: 1.0
      H: 72
      W: 72
    EXCEPT: false
  OPTIMIZER:
    EPS: 0.0001
    BETAS:
    - 0.9
    - 0.999
    MOMENTUM: 0.9
VALID:
  DATA:
    DATASET: BH
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: true
  DATA:
    FS: 15
    DATASET: BH
    SPECIFIC: high
    DO_PREPROCESS: true
    DATA_FORMAT: NDCHW
    DATA_PATH: /mnt/d/Document/Dataset/Pub_BH-rPPG_FULL
    CACHED_PATH: /mnt/d/Document/Dataset/Preprocessed
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: true
      CHUNK_LENGTH: 128
      DYNAMIC_DETECTION: false
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: true
      LARGE_FACE_BOX: true
      LARGE_BOX_COEF: 1.0
      H: 72
      W: 72
    EXCEPT: false
  SAVE_RESULT_NAME: SharedTrainedModel/results_npz/ttt_Physnet_BH_low.npz
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys-SCI
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH: production/models/ubfc_deepphys_NPLoss.pth
  ENHANCEMODEL_PATH: PreTrainedModels/BH_SizeW72_SizeH72_ClipLength128_DataTypeRaw_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.0_Dyamic_DetFalse_det_len128/bh_deepphys_Epoch49.pth
                    
